INSERT INTO zones (n, name, repop) VALUES (11, 'Турнирная арена тронного зала', NULL);
INSERT INTO zones (n, name, repop) VALUES (25, 'Летучий корабль', NULL);
INSERT INTO zones (n, name, repop) VALUES (38, '"Светлый" корабль артели Садко', NULL);
INSERT INTO zones (n, name, repop) VALUES (39, '"Темный" корабль артели Садко', NULL);
INSERT INTO zones (n, name, repop) VALUES (41, 'Пожня у деревни', NULL);
INSERT INTO zones (n, name, repop) VALUES (42, 'Раменье', NULL);
INSERT INTO zones (n, name, repop) VALUES (43, 'Болотце у околицы', NULL);
INSERT INTO zones (n, name, repop) VALUES (44, 'Темный лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (45, 'Посыльная дорога', NULL);
INSERT INTO zones (n, name, repop) VALUES (46, 'Дремучий лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (47, 'Холмы у реки', NULL);
INSERT INTO zones (n, name, repop) VALUES (48, 'Малиновый сад', NULL);
INSERT INTO zones (n, name, repop) VALUES (50, 'Новая мад-школа', NULL);
INSERT INTO zones (n, name, repop) VALUES (51, 'Заброшенный дом', NULL);
INSERT INTO zones (n, name, repop) VALUES (52, 'Лесная дорога', NULL);
INSERT INTO zones (n, name, repop) VALUES (53, 'Лесная поляна', NULL);
INSERT INTO zones (n, name, repop) VALUES (54, 'Птичий лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (55, 'Дальний хутор', NULL);
INSERT INTO zones (n, name, repop) VALUES (56, 'На реке', NULL);
INSERT INTO zones (n, name, repop) VALUES (58, 'На дороге', NULL);
INSERT INTO zones (n, name, repop) VALUES (63, 'Сторожевая башня', NULL);
INSERT INTO zones (n, name, repop) VALUES (64, 'Сказочный пустырь', NULL);
INSERT INTO zones (n, name, repop) VALUES (67, 'Степь у деревни', NULL);
INSERT INTO zones (n, name, repop) VALUES (70, 'Дорога прямоезжая', NULL);
INSERT INTO zones (n, name, repop) VALUES (71, 'Дорога прямоезжая', NULL);
INSERT INTO zones (n, name, repop) VALUES (72, 'Заброшенная мельница', NULL);
INSERT INTO zones (n, name, repop) VALUES (74, 'Лесное болото', NULL);
INSERT INTO zones (n, name, repop) VALUES (76, 'Глухой лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (79, 'Грибная поляна', NULL);
INSERT INTO zones (n, name, repop) VALUES (81, 'Птичий двор', NULL);
INSERT INTO zones (n, name, repop) VALUES (84, 'Тракт до Торжка', NULL);
INSERT INTO zones (n, name, repop) VALUES (85, 'Тракт до Торжка', NULL);
INSERT INTO zones (n, name, repop) VALUES (86, 'Дороги-дороги...', NULL);
INSERT INTO zones (n, name, repop) VALUES (89, 'Где-то в лесу', NULL);
INSERT INTO zones (n, name, repop) VALUES (92, 'Домик в деревне', NULL);
INSERT INTO zones (n, name, repop) VALUES (93, 'Два кладбища', NULL);
INSERT INTO zones (n, name, repop) VALUES (95, 'Дорога в медвежьей горе', NULL);
INSERT INTO zones (n, name, repop) VALUES (99, 'Жихарка', NULL);
INSERT INTO zones (n, name, repop) VALUES (100, 'Соловей-разбойник', NULL);
INSERT INTO zones (n, name, repop) VALUES (101, 'У Соловья в доме', NULL);
INSERT INTO zones (n, name, repop) VALUES (102, 'Три дороги - север', 30);
INSERT INTO zones (n, name, repop) VALUES (103, 'Три дороги - восток', 30);
INSERT INTO zones (n, name, repop) VALUES (104, 'Три дороги - запад', 30);
INSERT INTO zones (n, name, repop) VALUES (105, 'Логово людоедов', NULL);
INSERT INTO zones (n, name, repop) VALUES (110, 'Разбойничий притон', NULL);
INSERT INTO zones (n, name, repop) VALUES (111, 'Мятежная деревня', 40);
INSERT INTO zones (n, name, repop) VALUES (114, 'Охотничьи угодья Князя 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (115, 'Просека перед охотничьими угодьями', NULL);
INSERT INTO zones (n, name, repop) VALUES (116, 'Охотничьи угодья Князя', NULL);
INSERT INTO zones (n, name, repop) VALUES (117, 'Сказочный темный лес ("Хозяин леса")', NULL);
INSERT INTO zones (n, name, repop) VALUES (118, 'Кровавый Ворон', NULL);
INSERT INTO zones (n, name, repop) VALUES (120, 'В гостях у сказки', NULL);
INSERT INTO zones (n, name, repop) VALUES (121, 'Сказочный край', NULL);
INSERT INTO zones (n, name, repop) VALUES (123, 'Обезлюдевший хутор', NULL);
INSERT INTO zones (n, name, repop) VALUES (124, 'Пещеры Ночного Дозора', NULL);
INSERT INTO zones (n, name, repop) VALUES (127, 'Сказка лесных кошмаров', NULL);
INSERT INTO zones (n, name, repop) VALUES (130, 'Купальское ристалище', NULL);
INSERT INTO zones (n, name, repop) VALUES (132, 'Избушка на курьих ножках', NULL);
INSERT INTO zones (n, name, repop) VALUES (133, 'Чудская деревня', NULL);
INSERT INTO zones (n, name, repop) VALUES (135, 'Торговый тракт 4', NULL);
INSERT INTO zones (n, name, repop) VALUES (136, 'Дорога Искоростень-НК', NULL);
INSERT INTO zones (n, name, repop) VALUES (137, 'Зачарованный город', NULL);
INSERT INTO zones (n, name, repop) VALUES (138, 'Зачарованный город 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (140, 'Сказка о кузнеце-змееборце', NULL);
INSERT INTO zones (n, name, repop) VALUES (141, 'Про Федота-стрельца', NULL);
INSERT INTO zones (n, name, repop) VALUES (142, 'Необитаемый остров', NULL);
INSERT INTO zones (n, name, repop) VALUES (143, 'Летучий корабль', 20);
INSERT INTO zones (n, name, repop) VALUES (145, 'Кладбище', NULL);
INSERT INTO zones (n, name, repop) VALUES (149, 'Хоромы тверского боярина', NULL);
INSERT INTO zones (n, name, repop) VALUES (153, 'Лесной край', NULL);
INSERT INTO zones (n, name, repop) VALUES (155, 'В скифской усыпальнице', NULL);
INSERT INTO zones (n, name, repop) VALUES (157, 'Япония', NULL);
INSERT INTO zones (n, name, repop) VALUES (161, 'Япония 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (170, 'Сгоревший хутор', NULL);
INSERT INTO zones (n, name, repop) VALUES (201, 'Склеп', NULL);
INSERT INTO zones (n, name, repop) VALUES (202, 'Китеж-град', NULL);
INSERT INTO zones (n, name, repop) VALUES (203, 'Осада Китеж-града', NULL);
INSERT INTO zones (n, name, repop) VALUES (204, 'Малый китеж', NULL);
INSERT INTO zones (n, name, repop) VALUES (206, 'За помощью Князю', NULL);
INSERT INTO zones (n, name, repop) VALUES (220, 'Волчий лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (226, 'Деревенский Колодец', NULL);
INSERT INTO zones (n, name, repop) VALUES (230, 'Дорога Торжок-Русса 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (231, 'Дорога Торжок-Русса 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (232, 'Дорога Торжок-Русса 3', NULL);
INSERT INTO zones (n, name, repop) VALUES (235, 'Старая каменоломня', NULL);
INSERT INTO zones (n, name, repop) VALUES (236, 'Купеческий двор у Торжка', NULL);
INSERT INTO zones (n, name, repop) VALUES (240, 'Купеческий двор у Торжка', NULL);
INSERT INTO zones (n, name, repop) VALUES (241, 'Дорога к Ижорской деревне', 20);
INSERT INTO zones (n, name, repop) VALUES (242, 'Посолонь (Времена Года)', NULL);
INSERT INTO zones (n, name, repop) VALUES (248, 'Лагерь бешеных колобков', NULL);
INSERT INTO zones (n, name, repop) VALUES (251, 'Окрестности Переяславля', NULL);
INSERT INTO zones (n, name, repop) VALUES (254, 'Дорога по степи (Переяславль-Чернигов)', NULL);
INSERT INTO zones (n, name, repop) VALUES (255, 'Дорога в лесу 1 (Переяславль-Чернигов)', 20);
