INSERT INTO zones (n, name, repop) VALUES (11, 'Турнирная арена тронного зала', NULL);
INSERT INTO zones (n, name, repop) VALUES (25, 'Летучий корабль', NULL);
INSERT INTO zones (n, name, repop) VALUES (38, '"Светлый" корабль артели Садко', NULL);
INSERT INTO zones (n, name, repop) VALUES (39, '"Темный" корабль артели Садко', NULL);
INSERT INTO zones (n, name, repop) VALUES (41, 'Пожня у деревни', NULL);
INSERT INTO zones (n, name, repop) VALUES (42, 'Раменье', NULL);
INSERT INTO zones (n, name, repop) VALUES (43, 'Болотце у околицы', NULL);
INSERT INTO zones (n, name, repop) VALUES (44, 'Темный лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (45, 'Посыльная дорога', NULL);
INSERT INTO zones (n, name, repop) VALUES (46, 'Дремучий лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (47, 'Холмы у реки', NULL);
INSERT INTO zones (n, name, repop) VALUES (48, 'Малиновый сад', NULL);
INSERT INTO zones (n, name, repop) VALUES (50, 'Новая мад-школа', NULL);
INSERT INTO zones (n, name, repop) VALUES (51, 'Заброшенный дом', NULL);
INSERT INTO zones (n, name, repop) VALUES (52, 'Лесная дорога', NULL);
INSERT INTO zones (n, name, repop) VALUES (53, 'Лесная поляна', NULL);
INSERT INTO zones (n, name, repop) VALUES (54, 'Птичий лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (55, 'Дальний хутор', NULL);
INSERT INTO zones (n, name, repop) VALUES (56, 'На реке', NULL);
INSERT INTO zones (n, name, repop) VALUES (58, 'На дороге', NULL);
INSERT INTO zones (n, name, repop) VALUES (63, 'Сторожевая башня', NULL);
INSERT INTO zones (n, name, repop) VALUES (64, 'Сказочный пустырь', NULL);
INSERT INTO zones (n, name, repop) VALUES (67, 'Степь у деревни', NULL);
INSERT INTO zones (n, name, repop) VALUES (70, 'Дорога прямоезжая', NULL);
INSERT INTO zones (n, name, repop) VALUES (71, 'Дорога прямоезжая', NULL);
INSERT INTO zones (n, name, repop) VALUES (72, 'Заброшенная мельница', NULL);
INSERT INTO zones (n, name, repop) VALUES (74, 'Лесное болото', NULL);
INSERT INTO zones (n, name, repop) VALUES (76, 'Глухой лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (79, 'Грибная поляна', NULL);
INSERT INTO zones (n, name, repop) VALUES (81, 'Птичий двор', NULL);
INSERT INTO zones (n, name, repop) VALUES (84, 'Тракт до Торжка', NULL);
INSERT INTO zones (n, name, repop) VALUES (85, 'Тракт до Торжка', NULL);
INSERT INTO zones (n, name, repop) VALUES (86, 'Дороги-дороги...', NULL);
INSERT INTO zones (n, name, repop) VALUES (89, 'Где-то в лесу', NULL);
INSERT INTO zones (n, name, repop) VALUES (92, 'Домик в деревне', NULL);
INSERT INTO zones (n, name, repop) VALUES (93, 'Два кладбища', NULL);
INSERT INTO zones (n, name, repop) VALUES (95, 'Дорога в медвежьей горе', NULL);
INSERT INTO zones (n, name, repop) VALUES (99, 'Жихарка', NULL);
INSERT INTO zones (n, name, repop) VALUES (100, 'Соловей-разбойник', NULL);
INSERT INTO zones (n, name, repop) VALUES (101, 'У Соловья в доме', NULL);
INSERT INTO zones (n, name, repop) VALUES (102, 'Три дороги - север', 30);
INSERT INTO zones (n, name, repop) VALUES (103, 'Три дороги - восток', 30);
INSERT INTO zones (n, name, repop) VALUES (104, 'Три дороги - запад', 30);
INSERT INTO zones (n, name, repop) VALUES (105, 'Логово людоедов', NULL);
INSERT INTO zones (n, name, repop) VALUES (110, 'Разбойничий притон', NULL);
INSERT INTO zones (n, name, repop) VALUES (111, 'Мятежная деревня', 40);
INSERT INTO zones (n, name, repop) VALUES (114, 'Охотничьи угодья Князя 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (115, 'Просека перед охотничьими угодьями', NULL);
INSERT INTO zones (n, name, repop) VALUES (116, 'Охотничьи угодья Князя', NULL);
INSERT INTO zones (n, name, repop) VALUES (117, 'Сказочный темный лес ("Хозяин леса")', NULL);
INSERT INTO zones (n, name, repop) VALUES (118, 'Кровавый Ворон', NULL);
INSERT INTO zones (n, name, repop) VALUES (120, 'В гостях у сказки', NULL);
INSERT INTO zones (n, name, repop) VALUES (121, 'Сказочный край', NULL);
INSERT INTO zones (n, name, repop) VALUES (123, 'Обезлюдевший хутор', NULL);
INSERT INTO zones (n, name, repop) VALUES (124, 'Пещеры Ночного Дозора', NULL);
INSERT INTO zones (n, name, repop) VALUES (127, 'Сказка лесных кошмаров', NULL);
INSERT INTO zones (n, name, repop) VALUES (130, 'Купальское ристалище', NULL);
INSERT INTO zones (n, name, repop) VALUES (132, 'Избушка на курьих ножках', NULL);
INSERT INTO zones (n, name, repop) VALUES (133, 'Чудская деревня', NULL);
INSERT INTO zones (n, name, repop) VALUES (135, 'Торговый тракт 4', NULL);
INSERT INTO zones (n, name, repop) VALUES (136, 'Дорога Искоростень-НК', NULL);
INSERT INTO zones (n, name, repop) VALUES (137, 'Зачарованный город', NULL);
INSERT INTO zones (n, name, repop) VALUES (138, 'Зачарованный город 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (140, 'Сказка о кузнеце-змееборце', NULL);
INSERT INTO zones (n, name, repop) VALUES (141, 'Про Федота-стрельца', NULL);
INSERT INTO zones (n, name, repop) VALUES (142, 'Необитаемый остров', NULL);
INSERT INTO zones (n, name, repop) VALUES (143, 'Летучий корабль', 20);
INSERT INTO zones (n, name, repop) VALUES (145, 'Кладбище', NULL);
INSERT INTO zones (n, name, repop) VALUES (149, 'Хоромы тверского боярина', NULL);
INSERT INTO zones (n, name, repop) VALUES (153, 'Лесной край', NULL);
INSERT INTO zones (n, name, repop) VALUES (155, 'В скифской усыпальнице', NULL);
INSERT INTO zones (n, name, repop) VALUES (157, 'Япония', NULL);
INSERT INTO zones (n, name, repop) VALUES (161, 'Япония 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (170, 'Сгоревший хутор', NULL);
INSERT INTO zones (n, name, repop) VALUES (201, 'Склеп', NULL);
INSERT INTO zones (n, name, repop) VALUES (202, 'Китеж-град', NULL);
INSERT INTO zones (n, name, repop) VALUES (203, 'Осада Китеж-града', NULL);
INSERT INTO zones (n, name, repop) VALUES (204, 'Малый китеж', NULL);
INSERT INTO zones (n, name, repop) VALUES (206, 'За помощью Князю', NULL);
INSERT INTO zones (n, name, repop) VALUES (220, 'Волчий лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (226, 'Деревенский Колодец', NULL);
INSERT INTO zones (n, name, repop) VALUES (230, 'Дорога Торжок-Русса 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (231, 'Дорога Торжок-Русса 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (232, 'Дорога Торжок-Русса 3', NULL);
INSERT INTO zones (n, name, repop) VALUES (235, 'Старая каменоломня', NULL);
INSERT INTO zones (n, name, repop) VALUES (236, 'Купеческий двор у Торжка', NULL);
INSERT INTO zones (n, name, repop) VALUES (240, 'Купеческий двор у Торжка', NULL);
INSERT INTO zones (n, name, repop) VALUES (241, 'Дорога к Ижорской деревне', 20);
INSERT INTO zones (n, name, repop) VALUES (242, 'Посолонь (Времена Года)', NULL);
INSERT INTO zones (n, name, repop) VALUES (248, 'Лагерь бешеных колобков', NULL);
INSERT INTO zones (n, name, repop) VALUES (251, 'Окрестности Переяславля', NULL);
INSERT INTO zones (n, name, repop) VALUES (254, 'Дорога по степи (Переяславль-Чернигов)', NULL);
INSERT INTO zones (n, name, repop) VALUES (255, 'Дорога в лесу 1 (Переяславль-Чернигов)', 20);
INSERT INTO zones (n, name, repop) VALUES (257, 'Древние подземелья -- ДЗП', NULL);
INSERT INTO zones (n, name, repop) VALUES (258, 'История о хрустальном шаре', NULL);
INSERT INTO zones (n, name, repop) VALUES (260, 'Черное болото', 30);
INSERT INTO zones (n, name, repop) VALUES (266, 'Дорога к Замку Нежити', NULL);
INSERT INTO zones (n, name, repop) VALUES (268, 'Логово минотавров', NULL);
INSERT INTO zones (n, name, repop) VALUES (269, 'Свадьба на хуторе', NULL);
INSERT INTO zones (n, name, repop) VALUES (270, 'Болотце у околицы', NULL);
INSERT INTO zones (n, name, repop) VALUES (271, 'Речная пристань у Корсуни', NULL);
INSERT INTO zones (n, name, repop) VALUES (272, 'Проклятая деревня', NULL);
INSERT INTO zones (n, name, repop) VALUES (274, 'Дорога (Странная - Проклятая деревни)', NULL);
INSERT INTO zones (n, name, repop) VALUES (276, 'Поля и пастбища у Корсуни', NULL);
INSERT INTO zones (n, name, repop) VALUES (277, 'Разбойничий лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (278, 'Заколдованный лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (280, 'Стоянка половцев', NULL);
INSERT INTO zones (n, name, repop) VALUES (281, 'Боярская застава у Твери', 25);
INSERT INTO zones (n, name, repop) VALUES (282, 'Дорога до Твери', NULL);
INSERT INTO zones (n, name, repop) VALUES (283, 'По обе стороны дороги', NULL);
INSERT INTO zones (n, name, repop) VALUES (284, 'Дорога (Корсунь-Рыбацкая 2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (285, 'Дорога (Корсунь-Рыбацкая)', NULL);
INSERT INTO zones (n, name, repop) VALUES (286, 'Бобры и плотина', NULL);
INSERT INTO zones (n, name, repop) VALUES (287, 'Руины древнего города', NULL);
INSERT INTO zones (n, name, repop) VALUES (288, 'Храм Падшей Богини', NULL);
INSERT INTO zones (n, name, repop) VALUES (289, 'Дорога в лесу (Корсунь-Развалины)', NULL);
INSERT INTO zones (n, name, repop) VALUES (290, 'Дорога в степи (Корсунь-Развалины)', NULL);
INSERT INTO zones (n, name, repop) VALUES (291, 'Пещера Вдовы', NULL);
INSERT INTO zones (n, name, repop) VALUES (292, 'Травень остров', NULL);
INSERT INTO zones (n, name, repop) VALUES (293, 'Священный дуб', NULL);
INSERT INTO zones (n, name, repop) VALUES (295, 'Финист-ясен сокол', NULL);
INSERT INTO zones (n, name, repop) VALUES (296, 'Буратино', NULL);
INSERT INTO zones (n, name, repop) VALUES (303, 'Старая Ладога 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (305, 'Дорога в Ладогу', NULL);
INSERT INTO zones (n, name, repop) VALUES (306, 'Остров Валаам', NULL);
INSERT INTO zones (n, name, repop) VALUES (307, 'Странный Лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (308, 'Странный Лес 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (309, 'Дом Кудесницы Марьи', NULL);
INSERT INTO zones (n, name, repop) VALUES (318, 'Ристалище', NULL);
INSERT INTO zones (n, name, repop) VALUES (321, 'Снежная королева', NULL);
INSERT INTO zones (n, name, repop) VALUES (323, 'Князь Велесур и деревня язычников', NULL);
INSERT INTO zones (n, name, repop) VALUES (325, 'Дорога Искоростень-Туров 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (326, 'Дорога Искоростень-Туров 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (327, 'Морская стихия', NULL);
INSERT INTO zones (n, name, repop) VALUES (328, 'Дорога Менск-Туров 2', 20);
INSERT INTO zones (n, name, repop) VALUES (329, 'Дорога Менск-Туров', NULL);
INSERT INTO zones (n, name, repop) VALUES (330, 'Рыбацкая весь', 20);
INSERT INTO zones (n, name, repop) VALUES (331, 'Подводное царство', 30);
INSERT INTO zones (n, name, repop) VALUES (332, 'Подводное царство', 30);
INSERT INTO zones (n, name, repop) VALUES (333, 'Подводный город', NULL);
INSERT INTO zones (n, name, repop) VALUES (334, 'Пиратский остров', NULL);
INSERT INTO zones (n, name, repop) VALUES (335, 'Большие яры', NULL);
INSERT INTO zones (n, name, repop) VALUES (336, 'Окрестности Киева', NULL);
INSERT INTO zones (n, name, repop) VALUES (338, 'Передовой острог', NULL);
INSERT INTO zones (n, name, repop) VALUES (339, 'Разоренная деревня', NULL);
INSERT INTO zones (n, name, repop) VALUES (340, 'Дорога на запад от Киева', NULL);
INSERT INTO zones (n, name, repop) VALUES (342, 'Торговый тракт', NULL);
INSERT INTO zones (n, name, repop) VALUES (343, 'Торговый тракт 3', NULL);
INSERT INTO zones (n, name, repop) VALUES (346, 'Торговый тракт 4', NULL);
INSERT INTO zones (n, name, repop) VALUES (348, 'Торговый тракт 5', NULL);
INSERT INTO zones (n, name, repop) VALUES (351, 'Пристанище Лесомык', NULL);
INSERT INTO zones (n, name, repop) VALUES (352, 'Дорога', NULL);
INSERT INTO zones (n, name, repop) VALUES (353, 'Дорога Русса - Ершова слобода', NULL);
INSERT INTO zones (n, name, repop) VALUES (354, 'Ершова слобода', NULL);
INSERT INTO zones (n, name, repop) VALUES (355, 'Южный берег озера Ильмень', NULL);
INSERT INTO zones (n, name, repop) VALUES (360, 'Дорога южнее ВН', NULL);
INSERT INTO zones (n, name, repop) VALUES (361, 'Западный берег Ильмень', NULL);
INSERT INTO zones (n, name, repop) VALUES (378, 'Дорога к долине змеев', NULL);
INSERT INTO zones (n, name, repop) VALUES (379, 'Долина змеев', NULL);
INSERT INTO zones (n, name, repop) VALUES (380, 'Дорога от Корсуни на север', NULL);
INSERT INTO zones (n, name, repop) VALUES (381, 'Дорога от Корсуни на север 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (382, 'Постоялый двор', NULL);
INSERT INTO zones (n, name, repop) VALUES (383, 'Остров Буян', NULL);
INSERT INTO zones (n, name, repop) VALUES (384, 'Застава Черномора', NULL);
INSERT INTO zones (n, name, repop) VALUES (385, 'Погоревший лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (388, 'Замок Кащея бессмертного', NULL);
INSERT INTO zones (n, name, repop) VALUES (389, 'Дорога к странной деревне', NULL);
INSERT INTO zones (n, name, repop) VALUES (400, 'Хоромы брянского боярина', NULL);
INSERT INTO zones (n, name, repop) VALUES (421, 'Подземный Замок Проклятых', NULL);
INSERT INTO zones (n, name, repop) VALUES (422, 'Степная дорога до рыбацкой веси', NULL);
INSERT INTO zones (n, name, repop) VALUES (427, 'Мельня', NULL);
INSERT INTO zones (n, name, repop) VALUES (429, 'Торговый тракт 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (461, 'Сожженный лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (471, 'Черная дорога', NULL);
INSERT INTO zones (n, name, repop) VALUES (475, 'Погост у озера', NULL);
INSERT INTO zones (n, name, repop) VALUES (476, 'Дурман-трава', NULL);
INSERT INTO zones (n, name, repop) VALUES (477, 'Владимирская усадьба', NULL);
INSERT INTO zones (n, name, repop) VALUES (479, 'Лагерь разбойников', NULL);
INSERT INTO zones (n, name, repop) VALUES (500, 'Брюхо гриба?! Да ты обкурился, приятель!', NULL);
INSERT INTO zones (n, name, repop) VALUES (501, 'Киевский посад', NULL);
INSERT INTO zones (n, name, repop) VALUES (505, 'Странная деревня', NULL);
INSERT INTO zones (n, name, repop) VALUES (518, 'Болдины горы', NULL);
INSERT INTO zones (n, name, repop) VALUES (560, 'Хазарския крепость Саркел 28+', NULL);
INSERT INTO zones (n, name, repop) VALUES (568, 'Подземный город', NULL);
INSERT INTO zones (n, name, repop) VALUES (569, 'Погребенный город', NULL);
INSERT INTO zones (n, name, repop) VALUES (581, 'Окрестности Киева', NULL);
INSERT INTO zones (n, name, repop) VALUES (585, 'Лагерь отшельников Ночного Дозора', NULL);
INSERT INTO zones (n, name, repop) VALUES (600, 'Господин Великий Новгород', NULL);
INSERT INTO zones (n, name, repop) VALUES (601, 'Ганзейский двор', NULL);
INSERT INTO zones (n, name, repop) VALUES (603, 'Дорога НК-ВН 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (604, 'Дорога НК-ВН 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (606, 'Дорога к Ильмень-озеру', NULL);
INSERT INTO zones (n, name, repop) VALUES (607, 'На Ильмень-озере', NULL);
INSERT INTO zones (n, name, repop) VALUES (608, 'Приток Днепра 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (609, 'Приток Днепра 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (611, 'После Садко', NULL);
INSERT INTO zones (n, name, repop) VALUES (612, 'Дорога к топям', NULL);
INSERT INTO zones (n, name, repop) VALUES (613, 'Топи', 30);
INSERT INTO zones (n, name, repop) VALUES (614, 'Два богатыря', NULL);
INSERT INTO zones (n, name, repop) VALUES (615, 'Цыганский табор', NULL);
INSERT INTO zones (n, name, repop) VALUES (616, 'Заброшенная крепость', 20);
INSERT INTO zones (n, name, repop) VALUES (617, 'Дорога к заброшенной крепости', NULL);
INSERT INTO zones (n, name, repop) VALUES (618, 'Долина отрешенных', NULL);
INSERT INTO zones (n, name, repop) VALUES (619, 'Подземелье зла', NULL);
INSERT INTO zones (n, name, repop) VALUES (621, 'Варяжская деревня', 20);
INSERT INTO zones (n, name, repop) VALUES (622, 'Горемычная деревушка', NULL);
INSERT INTO zones (n, name, repop) VALUES (623, 'Дорога до Тотьмы 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (624, 'Дорога до Тотьмы 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (625, 'Дорога до Тотьмы 3', 30);
INSERT INTO zones (n, name, repop) VALUES (626, 'Воровская гильдия в Тотьме', NULL);
INSERT INTO zones (n, name, repop) VALUES (627, 'Чернигов-Курск 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (628, 'Чернигов-Курск 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (629, 'Чернигов-Курск 3', NULL);
INSERT INTO zones (n, name, repop) VALUES (631, 'Дорога к Новгородскому Посаду', NULL);
INSERT INTO zones (n, name, repop) VALUES (632, 'Дорога к чудской деревне', 15);
INSERT INTO zones (n, name, repop) VALUES (633, 'Дорога по Новгородским лесам', NULL);
INSERT INTO zones (n, name, repop) VALUES (634, 'Дорога к Новгородским селениям', NULL);
INSERT INTO zones (n, name, repop) VALUES (635, 'Лесной лабиринт', NULL);
INSERT INTO zones (n, name, repop) VALUES (636, 'Дальний хутор', NULL);
INSERT INTO zones (n, name, repop) VALUES (637, 'Дорога предков', NULL);
INSERT INTO zones (n, name, repop) VALUES (639, 'Дорога до Владимира 1', 20);
INSERT INTO zones (n, name, repop) VALUES (640, 'Новая мад-школа', NULL);
INSERT INTO zones (n, name, repop) VALUES (641, 'Дорога до Владимира 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (642, 'Дорога НК-ВН 3', 15);
INSERT INTO zones (n, name, repop) VALUES (643, 'Дорога вдоль Днепра (НК-ВН)', NULL);
INSERT INTO zones (n, name, repop) VALUES (644, 'Вышгород-Боярские хоромы', NULL);
INSERT INTO zones (n, name, repop) VALUES (647, 'Дорога до Пскова 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (648, 'Дорога до Пскова 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (649, 'Дорога до Пскова 3', NULL);
INSERT INTO zones (n, name, repop) VALUES (650, 'Дорога до Чернигова 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (651, 'Дорога до Чернигова 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (652, 'Дорога до Чернигова 3', NULL);
INSERT INTO zones (n, name, repop) VALUES (653, 'Дорога Чернигов-Брянск 1', 20);
INSERT INTO zones (n, name, repop) VALUES (654, 'Дорога Чернигов-Брянск 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (656, 'Дорога в Ижорские земли', NULL);
INSERT INTO zones (n, name, repop) VALUES (657, 'Дорога Владимир-Тверь (3)', NULL);
INSERT INTO zones (n, name, repop) VALUES (658, 'Дорога из Курска в Брянск', NULL);
INSERT INTO zones (n, name, repop) VALUES (659, 'Дорога из Курска в Брянск-2', NULL);
INSERT INTO zones (n, name, repop) VALUES (660, 'Брянск', NULL);
INSERT INTO zones (n, name, repop) VALUES (661, 'Новое брянское кладбище', NULL);
INSERT INTO zones (n, name, repop) VALUES (662, 'Тверская деревня', NULL);
INSERT INTO zones (n, name, repop) VALUES (665, 'Приднепровское селение', NULL);
INSERT INTO zones (n, name, repop) VALUES (666, 'Темница демонов (шестая зона ада)', NULL);
INSERT INTO zones (n, name, repop) VALUES (668, 'Новгородский гостинный двор', NULL);
INSERT INTO zones (n, name, repop) VALUES (669, 'Деревня в Новгородских лесах', NULL);
INSERT INTO zones (n, name, repop) VALUES (670, 'Замок темного мага', NULL);
INSERT INTO zones (n, name, repop) VALUES (671, 'Муромская деревня', NULL);
INSERT INTO zones (n, name, repop) VALUES (672, 'На реке Горынь', NULL);
INSERT INTO zones (n, name, repop) VALUES (675, 'Купеческая арена', NULL);
INSERT INTO zones (n, name, repop) VALUES (676, 'Пристань в Киеве', NULL);
INSERT INTO zones (n, name, repop) VALUES (677, 'Внутри вулкана (пятая зона ада)', NULL);
INSERT INTO zones (n, name, repop) VALUES (678, 'Путь в горах (четвертая зона ада)', NULL);
INSERT INTO zones (n, name, repop) VALUES (679, 'Пещера демонов (третья зона ада)', NULL);
INSERT INTO zones (n, name, repop) VALUES (682, 'Чернигов Курганы', NULL);
INSERT INTO zones (n, name, repop) VALUES (683, 'Деревушка у озера', NULL);
INSERT INTO zones (n, name, repop) VALUES (684, 'Осажденный лагерь', NULL);
INSERT INTO zones (n, name, repop) VALUES (686, 'Купеческий двор', NULL);
INSERT INTO zones (n, name, repop) VALUES (687, 'Туманный лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (688, 'Крепость Слободка близ Переяславля', NULL);
INSERT INTO zones (n, name, repop) VALUES (689, 'Дорога Чернигов-Любеч', NULL);
INSERT INTO zones (n, name, repop) VALUES (691, 'Вдоль мертвой реки (вторая зона ада)', NULL);
INSERT INTO zones (n, name, repop) VALUES (692, 'На распутье (первая зона ада)', NULL);
INSERT INTO zones (n, name, repop) VALUES (693, 'Марин Чертог', NULL);
INSERT INTO zones (n, name, repop) VALUES (694, 'Велесова Земля (Край Велеса)', NULL);
INSERT INTO zones (n, name, repop) VALUES (695, 'Школа волхвов', NULL);
INSERT INTO zones (n, name, repop) VALUES (700, 'Форпост викингов', NULL);
INSERT INTO zones (n, name, repop) VALUES (701, 'Дорога к форпосту викингов', NULL);
INSERT INTO zones (n, name, repop) VALUES (702, 'Словенская деревня(Курган)', NULL);
INSERT INTO zones (n, name, repop) VALUES (703, 'Сказочный сон', NULL);
INSERT INTO zones (n, name, repop) VALUES (704, 'Словенская деревня(проклятие)', NULL);
INSERT INTO zones (n, name, repop) VALUES (707, 'Мед поэзии', NULL);
INSERT INTO zones (n, name, repop) VALUES (710, 'Дорога Курск - Рязань (1)', NULL);
INSERT INTO zones (n, name, repop) VALUES (711, 'Дорога Курск - Рязань (2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (712, 'Тракт в Рязань', 20);
INSERT INTO zones (n, name, repop) VALUES (719, 'Дорога до Полоцка', NULL);
INSERT INTO zones (n, name, repop) VALUES (721, 'Дорога Тотьма-Рудники', NULL);
INSERT INTO zones (n, name, repop) VALUES (722, 'Хозяйка медной горы', NULL);
INSERT INTO zones (n, name, repop) VALUES (724, 'Медные рудники', NULL);
INSERT INTO zones (n, name, repop) VALUES (726, 'Дорога Владимир-Тверь 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (727, 'Дорога Полоцк-Минск', NULL);
INSERT INTO zones (n, name, repop) VALUES (731, 'Четыре стихии', NULL);
INSERT INTO zones (n, name, repop) VALUES (732, 'Дорога к Самоцветным горам и перевал', NULL);
INSERT INTO zones (n, name, repop) VALUES (748, 'Проклятая земля', NULL);
INSERT INTO zones (n, name, repop) VALUES (749, 'Веска Белай Русi', NULL);
INSERT INTO zones (n, name, repop) VALUES (751, 'Псков 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (752, 'Подземный Замок Проклятых', NULL);
INSERT INTO zones (n, name, repop) VALUES (753, 'Путь в Темную долину', NULL);
INSERT INTO zones (n, name, repop) VALUES (754, 'Лес Загубленных Душ', NULL);
INSERT INTO zones (n, name, repop) VALUES (755, 'Пустошь людских страхов(Темная долина)', NULL);
INSERT INTO zones (n, name, repop) VALUES (756, 'Пещеры Вечного Холода (Темная долина)', NULL);
INSERT INTO zones (n, name, repop) VALUES (759, 'Новая мад-школа', NULL);
INSERT INTO zones (n, name, repop) VALUES (760, 'Муром', NULL);
INSERT INTO zones (n, name, repop) VALUES (761, 'Заповедный лес', NULL);
INSERT INTO zones (n, name, repop) VALUES (762, 'Дорога в Муром часть 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (763, 'Сказочная дорога в Муром', NULL);
INSERT INTO zones (n, name, repop) VALUES (764, 'Дорога Муром - Тотьма 1', 20);
INSERT INTO zones (n, name, repop) VALUES (765, 'Дорога Муром - Тотьма 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (767, 'Дорога Муром - Тотьма 4', NULL);
INSERT INTO zones (n, name, repop) VALUES (771, 'Дорога из Минска на Псковский тракт', NULL);
INSERT INTO zones (n, name, repop) VALUES (773, 'Трактир в курской деревне', NULL);
INSERT INTO zones (n, name, repop) VALUES (774, 'Лукоморья больше нет', NULL);
INSERT INTO zones (n, name, repop) VALUES (778, 'Деревня ремесленников', NULL);
INSERT INTO zones (n, name, repop) VALUES (779, 'Дорога Галича - Деревня ремесленников', NULL);
INSERT INTO zones (n, name, repop) VALUES (789, 'Дальний север', NULL);
INSERT INTO zones (n, name, repop) VALUES (792, 'Лапландский колдун', NULL);
INSERT INTO zones (n, name, repop) VALUES (793, 'Гильдия душегубов', NULL);
INSERT INTO zones (n, name, repop) VALUES (794, 'Торговая лодья', NULL);
INSERT INTO zones (n, name, repop) VALUES (796, 'Гиблый яр', NULL);
INSERT INTO zones (n, name, repop) VALUES (797, 'Райковецкое селение', NULL);
INSERT INTO zones (n, name, repop) VALUES (798, 'Монгольский лагерь', NULL);
INSERT INTO zones (n, name, repop) VALUES (799, 'Ховала', NULL);
INSERT INTO zones (n, name, repop) VALUES (800, 'Степная дорога 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (801, 'Степная дорога 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (802, 'Степная дорога 3', NULL);
INSERT INTO zones (n, name, repop) VALUES (803, 'Два лагеря', NULL);
INSERT INTO zones (n, name, repop) VALUES (804, 'Детинец в степи', NULL);
INSERT INTO zones (n, name, repop) VALUES (806, 'Дикое поле', NULL);
INSERT INTO zones (n, name, repop) VALUES (807, 'Золотой идол', NULL);
INSERT INTO zones (n, name, repop) VALUES (808, 'Южный шлях - северная часть', NULL);
INSERT INTO zones (n, name, repop) VALUES (809, 'Южный шлях - южная часть', NULL);
INSERT INTO zones (n, name, repop) VALUES (829, 'Зимний замок', NULL);
INSERT INTO zones (n, name, repop) VALUES (830, 'Княжья псарня', NULL);
INSERT INTO zones (n, name, repop) VALUES (842, 'Принеси мне голову прекрасного принца', NULL);
INSERT INTO zones (n, name, repop) VALUES (850, 'Ростов Великий (Пригород)', NULL);
INSERT INTO zones (n, name, repop) VALUES (851, 'Ростов Великий', NULL);
INSERT INTO zones (n, name, repop) VALUES (852, 'Дорога Ростов-Тверь', NULL);
INSERT INTO zones (n, name, repop) VALUES (861, 'Замок тевтонских рыцарей', NULL);
INSERT INTO zones (n, name, repop) VALUES (862, 'Замок тевтонских рыцарей 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (863, 'от Пскова до Вислы', NULL);
INSERT INTO zones (n, name, repop) VALUES (864, 'от Вислы до Немана', 20);
INSERT INTO zones (n, name, repop) VALUES (865, 'Военный лагерь Миндовга', 20);
INSERT INTO zones (n, name, repop) VALUES (866, 'Таинственное поместье', NULL);
INSERT INTO zones (n, name, repop) VALUES (870, 'Волшебный сад', NULL);
INSERT INTO zones (n, name, repop) VALUES (877, 'Медное, серебряное и золотое царства', NULL);
INSERT INTO zones (n, name, repop) VALUES (888, 'Самоцветные горы 2 - подземные рудники', NULL);
INSERT INTO zones (n, name, repop) VALUES (899, 'Ливонский лагерь', NULL);
INSERT INTO zones (n, name, repop) VALUES (900, 'Тридевятое царство', NULL);
INSERT INTO zones (n, name, repop) VALUES (905, 'Зов крови 1', NULL);
INSERT INTO zones (n, name, repop) VALUES (906, 'Зов крови 2', NULL);
INSERT INTO zones (n, name, repop) VALUES (910, 'Рипейские горы - Хвангур', NULL);
INSERT INTO zones (n, name, repop) VALUES (911, 'Рипейские горы - Березань', NULL);
INSERT INTO zones (n, name, repop) VALUES (912, 'Рипейские горы - Алатырь', NULL);
INSERT INTO zones (n, name, repop) VALUES (914, 'Дорога к рипеям I (рипеи-1)', NULL);
INSERT INTO zones (n, name, repop) VALUES (915, 'Дорога к рипеям II (рипеи-1)', NULL);
INSERT INTO zones (n, name, repop) VALUES (916, 'Рипейские горы - дорога к ирию', NULL);
INSERT INTO zones (n, name, repop) VALUES (917, 'Дорога к реке смородине (рипеи-2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (918, 'Мост через реку Смородину (рипеи-2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (919, 'Переправа через реку Смородину (рипеи-2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (920, 'Развалины у реки Смородины (рипеи-2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (921, 'Царство мертвых (рипеи-2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (922, 'Логово Скипер зверя I (рипеи-2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (923, 'Логово Скипер зверя II (рипеи-2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (924, 'Царство мертвых (Огненное озеро) (рипеи-2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (925, 'Замок Огненного Змея I (рипеи-2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (926, 'Замок Огненного Змея II (рипеи-2)', NULL);
INSERT INTO zones (n, name, repop) VALUES (927, 'Подземный проход (рипеи-3)', NULL);
INSERT INTO zones (n, name, repop) VALUES (932, 'Ер-боко-каан', NULL);
INSERT INTO zones (n, name, repop) VALUES (935, 'Вий', NULL);
INSERT INTO zones (n, name, repop) VALUES (936, 'Курская деревня', NULL);
INSERT INTO zones (n, name, repop) VALUES (940, 'Аримаспы', NULL);
INSERT INTO zones (n, name, repop) VALUES (941, 'Царство змеиное', NULL);
INSERT INTO zones (n, name, repop) VALUES (951, 'Поселение наемников', NULL);
INSERT INTO zones (n, name, repop) VALUES (954, 'Ближние горы', NULL);
INSERT INTO zones (n, name, repop) VALUES (960, 'Баба-Яга (овраги)', NULL);
INSERT INTO zones (n, name, repop) VALUES (961, 'Баба-Яга 2 (лес)', NULL);
INSERT INTO zones (n, name, repop) VALUES (962, 'Баба-Яга 3 (горы)', NULL);
INSERT INTO zones (n, name, repop) VALUES (963, 'Прадуб', NULL);
INSERT INTO zones (n, name, repop) VALUES (964, 'Вальгалла', NULL);
INSERT INTO zones (n, name, repop) VALUES (965, 'Мидгард - мир людей', NULL);
INSERT INTO zones (n, name, repop) VALUES (1000, 'Порубежье  (переход РУСЬ-СТЕПЬ)', NULL);
INSERT INTO zones (n, name, repop) VALUES (1104, 'Бескрайняя степь', NULL);
INSERT INTO zones (n, name, repop) VALUES (1252, 'Мертвый город (храм)', NULL);
INSERT INTO zones (n, name, repop) VALUES (1253, 'Мертвый город', NULL);
INSERT INTO zones (n, name, repop) VALUES (1254, 'Ахуры и Дэвы', NULL);
INSERT INTO zones (n, name, repop) VALUES (3333, 'Посольство в Поднебесную', NULL);
